package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* lunes 18 de junio de 2018 08:08:09 PM CDT
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  void shutdown ();
} // interface AdditionOperations
