/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_coco_distribuidos;

import java.awt.Label;
import javax.swing.JButton;

/**
 *
 * @author Danae
 */
public class Libro extends javax.swing.JPanel {

    private int idLibro;
    private String vendedor;
    private double precio;
    /**
     * Creates new form Libro
     */
    public Libro(int idLibro, String vendedor, double precio) {
        initComponents();
        this.idLibro = idLibro;
        this.vendedor = vendedor;
        this.precio = precio;
    }

    public int getIdLibro() {
        return idLibro;
    }

    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }

    public String getVendedor() {
        return vendedor;
    }

    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }
    
    

    public JButton getBotonDevolver() {
        return BotonDevolver;
    }

    public void setBotonDevolver(JButton BotonDevolver) {
        this.BotonDevolver = BotonDevolver;
    }

    public Label getEstadoVenta() {
        return EstadoVenta;
    }

    public void setEstadoVenta(Label EstadoVenta) {
        this.EstadoVenta = EstadoVenta;
    }

    public Label getPublicacionAutor() {
        return PublicacionAutor;
    }

    public void setPublicacionAutor(Label PublicacionAutor) {
        this.PublicacionAutor = PublicacionAutor;
    }

    public Label getPublicacionDescripcion() {
        return PublicacionDescripcion;
    }

    public void setPublicacionDescripcion(Label PublicacionDescripcion) {
        this.PublicacionDescripcion = PublicacionDescripcion;
    }

    public Label getPublicacionPrecio() {
        return PublicacionPrecio;
    }

    public void setPublicacionPrecio(Label PublicacionPrecio) {
        this.PublicacionPrecio = PublicacionPrecio;
    }

    public Label getTitulo() {
        return Titulo;
    }

    public void setTitulo(Label Titulo) {
        this.Titulo = Titulo;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new java.awt.Label();
        EstadoVenta = new java.awt.Label();
        label4 = new java.awt.Label();
        PublicacionAutor = new java.awt.Label();
        label7 = new java.awt.Label();
        PublicacionPrecio = new java.awt.Label();
        label8 = new java.awt.Label();
        PublicacionDescripcion = new java.awt.Label();
        BotonDevolver = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        Titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Este es el  Titulo de mi libro ");

        EstadoVenta.setBackground(new java.awt.Color(216, 216, 216));
        EstadoVenta.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        EstadoVenta.setForeground(new java.awt.Color(255, 255, 255));
        EstadoVenta.setText("Comprado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(EstadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EstadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label4.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        label4.setForeground(new java.awt.Color(153, 153, 153));
        label4.setText("Autor:");

        PublicacionAutor.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        PublicacionAutor.setForeground(new java.awt.Color(102, 102, 102));
        PublicacionAutor.setText("Nombre del autor");

        label7.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        label7.setForeground(new java.awt.Color(153, 153, 153));
        label7.setText("Precio:");

        PublicacionPrecio.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        PublicacionPrecio.setForeground(new java.awt.Color(102, 102, 102));
        PublicacionPrecio.setText("$Precio");

        label8.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        label8.setForeground(new java.awt.Color(153, 153, 153));
        label8.setText("Descripcion:");

        PublicacionDescripcion.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        PublicacionDescripcion.setForeground(new java.awt.Color(102, 102, 102));
        PublicacionDescripcion.setText("yo soy la descripcion");

        BotonDevolver.setForeground(new java.awt.Color(153, 153, 153));
        BotonDevolver.setText("Devolver");
        BotonDevolver.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BotonDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDevolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PublicacionDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PublicacionAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PublicacionPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PublicacionAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PublicacionPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonDevolver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PublicacionDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDevolverMouseClicked
        // TODO add your handling code here:
        ConfirmacionDevolucion devolucion = new ConfirmacionDevolucion(idLibro, vendedor, precio);

        devolucion.setVisible(true);
    }//GEN-LAST:event_BotonDevolverMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDevolver;
    private java.awt.Label EstadoVenta;
    private java.awt.Label PublicacionAutor;
    private java.awt.Label PublicacionDescripcion;
    private java.awt.Label PublicacionPrecio;
    private java.awt.Label Titulo;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label4;
    private java.awt.Label label7;
    private java.awt.Label label8;
    // End of variables declaration//GEN-END:variables
}
