/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_coco_distribuidos;

import java.awt.Label;
import javax.swing.JButton;

/**
 *
 * @author Danae
 */
public class Vendo extends javax.swing.JPanel {
    private int idLibro;
    private String vendedor;
    private double precio;
    
    /**
     * Creates new form Vendo
     */
    public Vendo(int idLibro, String vendedor, double precio) {
        initComponents();
        this.idLibro = idLibro;
        this.vendedor = vendedor;
        this.precio = precio;
    }

    public Label getTituloVenta() {
        return tituloVenta;
    }

    public void setTituloVenta(Label tituloVenta) {
        this.tituloVenta = tituloVenta;
    }
    
    

    public JButton getBotonComprar() {
        return BotonComprar;
    }

    public void setBotonComprar(JButton BotonComprar) {
        this.BotonComprar = BotonComprar;
    }
    
    

    public Label getEstadoVenta() {
        return EstadoVenta;
    }

    public void setEstadoVenta(Label EstadoVenta) {
        this.EstadoVenta = EstadoVenta;
    }

    public Label getPublicacionAutor() {
        return PublicacionAutor;
    }

    public void setPublicacionAutor(Label PublicacionAutor) {
        this.PublicacionAutor = PublicacionAutor;
    }

    public Label getPublicacionDescripcion() {
        return PublicacionDescripcion;
    }

    public void setPublicacionDescripcion(Label PublicacionDescripcion) {
        this.PublicacionDescripcion = PublicacionDescripcion;
    }

    public Label getPublicacionPrecio() {
        return PublicacionPrecio;
    }

    public void setPublicacionPrecio(Label PublicacionPrecio) {
        this.PublicacionPrecio = PublicacionPrecio;
    }

    public int getIdLibro() {
        return idLibro;
    }

    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }

    public String getVendedor() {
        return vendedor;
    }

    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloVenta = new java.awt.Label();
        EstadoVenta = new java.awt.Label();
        label4 = new java.awt.Label();
        label7 = new java.awt.Label();
        BotonComprar = new javax.swing.JButton();
        PublicacionPrecio = new java.awt.Label();
        PublicacionDescripcion = new java.awt.Label();
        PublicacionAutor = new java.awt.Label();
        label8 = new java.awt.Label();

        setPreferredSize(new java.awt.Dimension(534, 320));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        tituloVenta.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tituloVenta.setForeground(new java.awt.Color(255, 255, 255));
        tituloVenta.setText("Yo soy el Titulo de la venta ");

        EstadoVenta.setBackground(new java.awt.Color(255, 102, 102));
        EstadoVenta.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        EstadoVenta.setForeground(new java.awt.Color(255, 255, 255));
        EstadoVenta.setText("Disponible");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tituloVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EstadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EstadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label4.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        label4.setForeground(new java.awt.Color(153, 153, 153));
        label4.setText("Autor:");

        label7.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        label7.setForeground(new java.awt.Color(153, 153, 153));
        label7.setText("Precio:");

        BotonComprar.setForeground(new java.awt.Color(153, 153, 153));
        BotonComprar.setText("Comprar");
        BotonComprar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BotonComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonComprarMouseClicked(evt);
            }
        });
        BotonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprarActionPerformed(evt);
            }
        });

        PublicacionPrecio.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        PublicacionPrecio.setForeground(new java.awt.Color(102, 102, 102));
        PublicacionPrecio.setText("$Precio");

        PublicacionDescripcion.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        PublicacionDescripcion.setForeground(new java.awt.Color(102, 102, 102));
        PublicacionDescripcion.setText("yo soy la descripcion");

        PublicacionAutor.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        PublicacionAutor.setForeground(new java.awt.Color(102, 102, 102));
        PublicacionAutor.setText("Nombre del autor");

        label8.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        label8.setForeground(new java.awt.Color(153, 153, 153));
        label8.setText("Descripcion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PublicacionDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PublicacionAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PublicacionPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(BotonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PublicacionAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PublicacionPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BotonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PublicacionDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonComprarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BotonComprarMouseClicked

    private void BotonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprarActionPerformed
        // TODO add your handling code here:
        ConfirmacionCompra compra =new ConfirmacionCompra(idLibro, vendedor, precio);
        compra.setVisible(true);
    }//GEN-LAST:event_BotonComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonComprar;
    private java.awt.Label EstadoVenta;
    private java.awt.Label PublicacionAutor;
    private java.awt.Label PublicacionDescripcion;
    private java.awt.Label PublicacionPrecio;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label4;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label tituloVenta;
    // End of variables declaration//GEN-END:variables
}
